# Generated by Django 2.0 on 2019-06-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltExam_app', '0006_auto_20190624_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='joined_by',
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
